---
title: "LIN 200-210"
subtitle: "How to Create Your Own Language"
author: "Dr. Andrew M. Byrd"
date: "Fall 2026"
format:
  pdf:
    documentclass: scrartcl
    papersize: letter
    fontsize: 12pt
    mainfont: "Libertinus Serif"
    geometry: margin=1in
    pdf-engine: xelatex
editor: source
markdown:
  wrap: 72
---

## Course Information

| | |
|---|---|
| **Course Developer/Instructor** | Dr. Andrew M. Byrd |
| **Course Meeting Time** | MWF 10-10:50, Lewis Hall U135 |
| **Office Hours** | Tuesday 10-11, in person, POT 1667; Thursday 10-11, on Zoom |

**Andrew Byrd** — Instructor, Linguistics

[andrewbyrd@uky.edu](mailto:andrewbyrd@uky.edu)

Office Hours: Tuesday 10-11, in person (POT 1667); Thursday 10-11, on Zoom

- This is an in-person course, though much of the course content is delivered remotely. To access the course visit uky.edu/canvas and login to Canvas with your LINK BLUE username and password.
- All times listed throughout this syllabus are Eastern Standard Times (EST); please plan accordingly if you are in a different time zone.
- You will want to refer to this syllabus and course schedule frequently throughout the course.

## Contacting the Instructor

1. **The best way to contact the instructor:** You can get in touch with Dr. Byrd either through comments in the OneDrive docx, email ([andrewbyrd@uky.edu](mailto:andrewbyrd@uky.edu)), or the Discord server.

2. **For questions related to the course material, lectures, assignments, etc.:** Post a question to Discord, within the "conlang-help" channel. This will allows others to view your question and the reply, as well as you to see others' questions. If you have a question that has not already been asked by another student, then you may post it, which will allow all other students to see your question and the instructor response. The material we cover in this class can be difficult and many students often have the same questions, so please don't hesitate to post them.

3. **For technical assistance with Canvas:** For any technical problems with Canvas — links that won't work, pages that won't appear, connections that are lost, assignments that are technically unable to be submitted — please visit [https://community.canvaslms.com/docs/DOC-10554-4212710328](https://community.canvaslms.com/docs/DOC-10554-4212710328), where you may receive support using a variety of methods. If consulting via e-mail, be sure to send a copy your email that explains the technical difficulty to me at [andrewbyrd@uky.edu](mailto:andrewbyrd@uky.edu). You may also call Canvas at 1-844-480-0838. I am not a technology expert, by any means, so please do not ask me for technical assistance.

4. **For any question or issue not specifically related to the material, lecture, homework, etc.:** Please email [andrewbyrd@uky.edu](mailto:andrewbyrd@uky.edu). You may visit [http://www.uky.edu/UKIT/](http://www.uky.edu/UKIT%20/) or call 859-218-HELP to speak with the Information Technology Customer Service Center. For assistance with Distance Learning Programs, visit [http://www.uky.edu/ukonline/](http://www.uky.edu/ukonline/).

For all electronic correspondence (Canvas and email), I will typically reply within 24 hours to the next business day, EST.

**Questions posted on Discord (or any email correspondences received) after 3pm will be answered the next business day.**

Waiting on a response for a question posted/emailed after 3pm does not excuse the student from completing an assignment, so students should plan ahead and ask their questions well in advance of due dates.

## Course Description

In 1910, J.R.R. Tolkien began construction of a fictional language of the Elves, which ultimately resulted in the creation of at least fifteen different languages and dialects. Why would someone create their own language? And how would a person begin to even do so? In this course, we will answer both questions directly, addressing the impetus for language invention and the process by which one creates a language. By examining a variety of invented languages (such as Esperanto, Klingon, and Dothraki) and natural languages (such as Spanish, Swahili, and Chinese), we will examine how language works in general and the typical features found within the languages of the world. Throughout the course, students will work on their own languages in stages, concluding with a presentation of their work to the other students at the end of the semester.

## Prerequisites

There are no prerequisites for this course.

## Course Goals

By the end of this course, students will be able to:

1. Identify the major subfields of linguistic study;
2. Identify the various types of constructed languages;
3. Be able to describe and recognize the basic linguistic features found in the languages of the world;
4. Be able to incorporate these features into an original language;
5. Create a final product that demonstrates concepts learned throughout the semester and incorporates aspects of both synthesis and analysis.

## Learning Outcomes

In this course, students will personally produce, present, and perform a language of their own creation. It is in this way that the learning of language creation is a type of process-focused creativity, one which will be fostered through input given by the instructor and fellow students. As a part of this process:

1. Students will learn to define and distinguish different approaches to creativity as appropriate to language creation.
2. Through constraint-focused creativity, students will apply natural linguistic laws and constraints to their languages, which determine what constitutes a human language; or, if designing a non-human language, deliberately violate these laws and constraints in its production;
3. Students will be able to demonstrate the ability to critically analyze work produced by other students in the course through assessments of project components, which incorporate their understanding of the history of constructed languages, the theory that lies behind them, and the cultural factors that determine what is an appropriate choice for an invented language;
4. Throughout the course, students will evaluate the results of their own language creation, and using that evaluation, reassess and refine their work.

## Required Materials

Peterson, David J. 2015. *The Art of Language Invention*. New York: Penguin Books.

## Helpful Websites

There are a number of helpful websites out there to get you started in the creation of your own conlang. Some of these include:

1. [https://www.zompist.com/kit.html](https://www.zompist.com/kit.html)
2. [https://www.zompist.com/lck2.html](https://www.zompist.com/lck2.html)
3. [https://conlang.fandom.com/wiki/Portal:Main](https://conlang.fandom.com/wiki/Portal:Main)
4. [https://forum.unilang.org/index.php](https://forum.unilang.org/index.php)
5. [https://www.reddit.com/r/conlangs/](https://www.reddit.com/r/conlangs/)
6. [https://conlang.org/](https://conlang.org/)

## Description of Course Activities and Assignments

Throughout the semester, students will be asked to read select passages from the assigned readings, watch short videos that immerse the students into the specific topic at hand, and then complete on-line activities through which the students may practice the information gained that day. Students will also participate and turn in exercises and activities in class.

## Course Assignments

Throughout the semester, students will be asked to complete:

| | | |
|---:|---|---|
| 1. | Comprehension quizzes on videos & readings | 20% |
| 2. | 4 project components | 40% |
| 3. | In-class participation | 30% |
| 4. | 1 final project worth 20 points | 10% |
| **Total** | | **100%** |

## Summary Description of Course Assignments

In addition to the on-line activities that follow each video, students will work on a large project in which they will create their own invented language. Progress will be monitored at four separate stages of the class, and their product will be produced within a small pre-selected groups of students designed to foster community interaction.

## Course Project

The primary focus of this course will be for students to create their own language, with progress split up into four separate stages.

**Project Component 1:** What is the name and idea for your group's invented language? What culture is it based in?

**Project Component 2:** What are the sounds of your group's language? How are they organized?

**Project Component 3:** How are words put together and arranged in your group's language?

**Project Component 4:** What is the history & writing system of your group's language?

Once component 4 has been turned in and assessed, students will then be ready to finish work on the complete product. There are two components to this final project: (1) a recorded performance (such as a video recording of a dialogue or poem) delivered in your invented language and (2) a complete description and analysis of the language.

## Group Collaboration

You will be teaming up with 2-3 other group members, who you will work with in-class in learning how to build languages. Thus, in-class attendance is a crucial component. You will also practice working on the individual aspects of the projects through in-class activities.

## Course Grading

The grading scale will be as follows:

90–100% = A     80–89% = B     70–79% = C     60–69% = D     Below 60% = E

## Tentative Course Schedule

### Component 1

- The languages of *Star Wars* — What is a Language? — Reading: Peterson 1-24
- Enochian, Volapük, and Lojban — The History and Types of Invented Languages — Reading: [http://www.joerg-rhiemeier.de/Conlang/history.html](http://www.joerg-rhiemeier.de/Conlang/history.html)
- The Languages of *Warcraft* — Language Ideology & Culture — Reading: [https://open.library.ubc.ca/media/download/pdf/24/1.0368688/4](https://open.library.ubc.ca/media/download/pdf/24/1.0368688/4)

**ASSIGNMENT:** Project Component 1 due

### Component 2

- Klingon (*Star Trek*) — Consonants — Reading: Peterson 25-40
- Jutoon (*Doctor Who*) — Vowels — Reading: Peterson 40-46
- Dothraki & High Valerian (*Game of Thrones*) — Phonotactics — Reading: Peterson 46-61
- Láadan (*Native Tongue*) — Prosody — Reading: Peterson 61-87

**ASSIGNMENT:** Project Component 2 due

### Component 3

- *A Clockwork Orange*, *1984* — The Lexicon — Reading: Jackson - Invented Vocabularies.pdf
- Winja, Udam, and His-hílax (*Far Cry Primal*) — Nouns — Reading: Peterson 97-135
- Na'vi (*Avatar*) — Verbs — Reading: Peterson 136-148
- Belter (*The Expanse*) — Word Order — Reading: Peterson 148-152

**ASSIGNMENT:** Project Component 3 due

### Component 4

- The Languages of J.R.R. Tolkien's Universe — Language Families — Reading: Peterson 159-178
- Brithenig — Language Change — Reading: Peterson 178-207
- The Scripts of Hyrule (*The Legend of Zelda*) — Writing Sounds — Reading: Peterson 209-228
- Heptapod (*Arrival*) — Writing Words — Reading: Peterson 228-258

**ASSIGNMENT:** Project Component 4 due

## Final Exam Information

There will be no final exam in this course.

## Mid-term Grade (for 100-400 level courses, and for undergrads in 500-level courses)

Mid-term grades will be posted in myUK by the deadline established in the Academic Calendar ([http://www.uky.edu/registrar/calendar](http://www.uky.edu/registrar/calendar)).

## Submission of Assignments

Assignments will be submitted on-line through Canvas. Late assignments will be accepted only in the event of documented excused inability/absences.

Appropriate documentation for the following should be sent to the instructor at [andrewbyrd@uky.edu](mailto:andrewbyrd@uky.edu) as soon as possible—at least two days before the assignment is missed so that the student and instructor can make arrangements for any missed work:

- Significant Illness: letterhead with an address, fax, and phone number of a health care professional should be given with a statement that the student was too sick to use a computer. Regular doctor appointments are not considered "significant" illness and no extensions or concessions will be granted for this reason.
- University-Sponsored Trips: Official letters from the University are required as evidence of university approval. These can be scanned and emailed to the instructor or you can contact the instructor for mailing directions.
- If there is a death in your immediate household or family, you can email the instructor a link to the obituary or mail a copy of a service program. These can be scanned and emailed to the instructor or you can contact the instructor for mailing directions.

Problems associated with your computer, procrastination, vacation time, transportation issues, and/or "life issues" in general are not acceptable excuses for late submission of assignments. It is your responsibility to make sure that you access and submit assignments on time.

## Technical Requirements

In order to have a successful educational experience in flipped classes, there are minimum technology requirements that should be met. The University of Kentucky strongly recommends that each student purchase a personal computer. To review minimum recommendations and guidelines for your computer click [here](http://www.uky.edu/ukit/hardwareguide).

University of Kentucky distance learning students are also required to acquire the following hardware, software, and Internet connection to ensure that all systems used by distance learning courses will function properly.

| Hardware: | Software: | Internet Connection: |
|---|---|---|
| Headset with a microphone | The latest version of Adobe Flash ([available here](http://get.adobe.com/flashplayer/)) | 5 Mbps Broadband Connection Minimum |
| Webcam | The latest version of Adobe Acrobat Reader ([available here](http://get.adobe.com/reader/)) | |
| | Microsoft Office ([available free to students here](http://download.uky.edu/)) | |

## Technical Difficulties

Contact Information for UK's Information Technology Customer Service Center

## Attendance Policy

The course is designed for regular, and meaningful participation in each MWF class. In order to participate in group activities and receive feedback on your conlang ideas, you are expected to come every day.

## Excused Absences

Students need to notify the professor of absences prior to class when possible. The following are acceptable reasons for excused absences: (a) serious illness, (b) illness or death of family member, (c) University-related trips, (d) major religious holidays, (e) interviews for full-time job opportunities post-graduation and interviews for graduate or professional school, and (f) other circumstances found to fit "reasonable cause for nonattendance" by the professor.

Students anticipating an absence for a major religious holiday are responsible for notifying the instructor in writing of anticipated absences due to their observance of such holidays no later than the last day in the semester to add a class. Two weeks prior to the absence is reasonable, but should not be given any later. Information regarding major religious holidays may be obtained through the Ombud (859-257-3737, [http://www.uky.edu/Ombud/ForStudents_ExcusedAbsences.php](http://www.uky.edu/Ombud/ForStudents_ExcusedAbsences.php)).

Students are expected to withdraw from the class if more than 20% of the classes scheduled for the semester are missed (excused) per University policy.

Students missing any graded work due to an excused absence are responsible: for informing the Instructor of Record about their excused absence within one week following the period of the excused absence (except where prior notification is required); and for making up the missed work. The professor must give the student an opportunity to make up the work and/or the exams missed due to an excused absence, and shall do so, if feasible, during the semester in which the absence occurred.

## Academic Integrity

Per University policy, students shall not plagiarize, cheat, or falsify or misuse academic records. Students are expected to adhere to University policy on cheating and plagiarism in all courses. The minimum penalty for a first offense is a zero on the assignment on which the offense occurred. If the offense is considered severe or the student has other academic offenses on their record, more serious penalties, up to suspension from the University may be imposed.

Plagiarism and cheating are serious breaches of academic conduct. Each student is advised to become familiar with the various forms of academic dishonesty as explained in the Code of Student Rights and Responsibilities. Complete information can be found at the following website: [http://www.uky.edu/Ombud](http://www.uky.edu/Ombud). A plea of ignorance is not acceptable as a defense against the charge of academic dishonesty. It is important that you review this information as all ideas borrowed from others need to be properly credited.

All academic work, written or otherwise, submitted by students to their instructors or other academic supervisors, is expected to be the result of their own thought, research, or self-expression. In cases where students feel unsure about a question of plagiarism involving their work, they are obliged to consult their instructors on the matter before submission.

When students submit work purporting to be their own, but which in any way borrows ideas, organization, wording, or content from another source without appropriate acknowledgment of the fact, the students are guilty of plagiarism.

Plagiarism includes reproducing someone else's work (including, but not limited to a published article, a book, a website, computer code, or a paper from a friend) without clear attribution. Plagiarism also includes the practice of employing or allowing another person to alter or revise the work, which a student submits as his/her own, whoever that other person may be. Students may discuss assignments among themselves or with an instructor or tutor, but when the actual work is done, it must be done by the student, and the student alone.

When a student's assignment involves research in outside sources or information, the student must carefully acknowledge exactly what, where and how he/she has employed them. If the words of someone else are used, the student must put quotation marks around the passage in question and add an appropriate indication of its origin. Making simple changes while leaving the organization, content, and phraseology intact is plagiaristic. However, nothing in these Rules shall apply to those ideas, which are so generally and freely circulated as to be a part of the public domain.

## Appropriate Online Behavior

- Students are expected to maintain civility and decorum in all language used on Canvas (including Discussion Board posts) and in email correspondence. Language should demonstrate respect for other students and the instructor.
- Students are expected to regularly log in to the course (once daily, Monday-Fridays), and to demonstrate an attitude that seeks to take full advantage of the educational opportunity. All students are expected to be prepared to work and actively engage in learning. The student is responsible for his/her own learning.
- Virtual communication and discussion "in cyberspace" occur in a social environment where normal rules of social interaction apply. The remoteness of the recipients is no excuse to behave in an antisocial manner and post unacceptable messages. Unacceptable messages include those that harass, intimidate, threaten, belittle, ridicule, express hatred for, or aggression toward others. Let us be mindful to avoid words that imply that some groups of people are less worthy than others (e.g., avoid racist, sexist, anti-Semitic, age-ist, and homophobic language, or language that is degrading or harassing in any other way). Any such posts should be reported to the instructor immediately.
- Discussion board and other electronic communication for this course should relate only to the course subject matter, generally respond to the instructor threads, and always seek to further the aims of that particular discussion forum or chat session (e.g., stay on topic). Contributions to discussion boards and synchronous chat are the intellectual property of the authors.
- Students who quote another person in class projects, publications or even in remarks made on the discussion board should always acknowledge the source of that quote (e.g., do not plagiarize your classmates).
- Do not copy private messages to another person without the author's explicit permission.

## Information on Distance Learning Library Services

- Carla Cantagallo, DL Librarian
- Web: [http://libraries.uky.edu/DLLS](http://libraries.uky.edu/DLLS)
- Phone: 859 218-1240
- Email: [carla@.uky.edu](mailto:carla@.uky.edu)
- DL Interlibrary Loan Service: [http://libraries.uky.edu/ILL](http://libraries.uky.edu/ILL)

## Accommodations due to disability

If you have a documented disability that requires academic accommodations, please see me as soon as possible during scheduled office hours. In order to receive accommodations in this course, you must provide me with a Letter of Accommodation from the Disability Resource Center (DRC). The DRC coordinates campus disability services available to students with disabilities. It is located on the corner of Rose Street and Huguelet Drive in the Multidisciplinary Science Building, Suite 407. You can reach them via phone at (859) 257-2754 and via email at [drc@uky.edu](mailto:drc@uky.edu). Their web address is [http://www.uky.edu/DisabilityResourceCenter](http://www.uky.edu/DisabilityResourceCenter).

## Non-Discrimination Statement and Title IX Information

The University of Kentucky faculty are committed to supporting students and upholding the University's non-discrimination policy.

Discrimination is prohibited at UK. If you experience an incident of discrimination we encourage you to report it to Institutional Equity & Equal Opportunity (IEEO) Office, 13 Main Building, (859) 257-8927.

### Statement on Diversity, Equity, and Inclusion

Before the dissolution of the University Senate, the University of Kentucky was is committed to our core values of diversity and inclusion, mutual respect and human dignity, and a sense of community. However, for reasons that I will not discuss here, this is no longer the case.

The following is a previous statement of DEI put forth by the Senate, which I still stand by:

"We acknowledge and respect the seen and unseen diverse identities and experiences of all members of the university community (https://www.uky.edu/regs/gr14). These identities include but are not limited to those based on race, ethnicity, gender identity and expressions, ideas and perspectives, religious and cultural beliefs, sexual orientation, national origin, age, ability, and socioeconomic status. We are committed to equity and justice and providing a learning and engaging community in which every member is engaged, heard, and valued.

We strive to rectify and change behavior that is inconsistent with our principles and commitment to creating a safe, equitable, and anti-racist environment. If students encounter such behavior in a course, they are encouraged to speak with the instructor of record or the college's diversity officer, who is charged with addressing concerns about diversity, equity, and inclusiveness. Students may also contact a faculty member within the department, program director, the director of undergraduate or graduate studies, the department chair, or the dean. To submit an official report of bias, hatred, racism, or identity-based violence, visit the Bias Incident Support Services website (https://www.uky.edu/biss/report-bias-incident)."

### Acts of Sex- and Gender-Based Discrimination or Interpersonal Violence

If you experience an incident of sex- or gender-based discrimination or interpersonal violence, we encourage you to report it. While you may talk to a faculty member or TA/RA/GA, understand that as a "Responsible Employee" of the University these individuals MUST report any acts of violence (including verbal bullying and sexual harassment) to the University's Title IX Coordinator in the IEEO Office. If you would like to speak with someone who may be able to afford you confidentiality, the Violence Intervention and Prevention (VIP) program (Frazee Hall – Lower Level; [http://www.uky.edu/vipcenter/](http://www.uky.edu/vipcenter/)), the Counseling Center (106 Frazee Hall, [http://www.uky.edu/counselingcenter/](http://www.uky.edu/counselingcenter/)) and the University Health Services ([https://ukhealthcare.uky.edu/university-health-service/student-health](https://ukhealthcare.uky.edu/university-health-service/student-health)) are confidential resources on campus.
